pages:
  image: hrektts/mdbook
  script:
  - mdbook build book
  - mv book/book public
  artifacts:
    paths:
    - public

test:
  image: rust:1-stretch
  script:
  - rustup override set nightly
  - cargo run
  artifacts:
    paths:
    - target
