[package]
name = "kiln"
version = "0.2.0"
authors = ["swissChili"]
edition = "2018"
description = "A library-only relational database"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
uuid = { version = "0.7", features = ["v4"] }
