[package]
name = "kiln"
version = "0.1.3"
authors = ["swissChili"]
edition = "2018"
description = "A WIP relational database"
license = "GPL-3.0"
readme = "README.md"

[dependencies]
uuid = { version = "0.7", features = ["v4"] }
